### ISSUE TITLE
Freshly-built container is deleted before use (typo?)

### ISSUE THREAD

**Issue by ben-alkov** [samp1044/signal-appimage#2]
https://github.com/samp1044/signal-appimage/blob/44a7105e8526bd0531b29cc7628c739375209b43/run.sh#L3-L4

**Comment by samp1044** [comment]
The intention was, if for some reason a container with that name already runs, that container should be stopped and removed so that the new container can be started without collisions. Don't know if its the best approach to archieve that?

**Comment by ben-alkov** [comment]
> Don't know if its the best approach to archieve that?

Not sure, but what I was seeing was that the *next* line (`docker run -v ./release:/release -it --name buildsignal buildsignal`) would fail on being unable to find the 'buildsignal' container.

Either way, the "stop/rm" **must** happen *before* the new container is built (otherwise, you're deleting the container you just built).
